# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    xcov(
  		workspace: "RocketX.xcworkspace",
  		scheme: "RocketX",
  		output_directory: "test_output",
  		exclude_targets: "Pods_RocketX.framework,Pods_RocketXTests.framework,Pods_RocketX_RocketXUITests.framework,SDWebImage.framework"
	)
  end
end
