# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RocketX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage', '~> 5.0'

  target 'RocketXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RocketXUITests' do
    # Pods for testing
  end

end
